"""Render a plan's scorecard as a diagnostic: HTML, and PDF via headless Chromium
(Playwright). The HTML is the in-app page; the PDF is what a founder gets sent."""
from html import escape
import os
import subprocess
import tempfile

from ..models import Company, Plan

LABEL = {"founder_distribution": "Founder distribution", "icp_attention": "ICP attention",
         "search": "Search", "launches": "Launches", "onboarding": "Onboarding & conversion"}


def _bar(score: int) -> str:
    return f'<div class="bar"><div class="fill" style="width:{score * 10}%"></div></div>'


def scorecard_html(company: Company, plan: Plan) -> str:
    sc, nar = plan.scorecard, plan.scorecard.get("_narrative", {})
    e = escape
    rows = ""
    for ch in LABEL:
        c = sc.get(ch)
        if not c:
            continue
        rows += f"""
        <section class="ch">
          <div class="head"><h3>{LABEL[ch]}</h3><div class="score">{c['score']}<span>/10</span></div></div>
          {_bar(c['score'])}
          <ul>{''.join(f'<li>{e(r)}</li>' for r in c['rationale'])}</ul>
          {f'<p class="interp">{e(c["interpretation"])}</p>' if c.get('interpretation') else ''}
          <div class="fix"><strong>Fix:</strong> {e(c['fix'])}</div>
        </section>"""
    seq_rows = "".join(
        f"<tr><td>Weeks {s['start_week']}–{s['end_week']}</td><td>{LABEL.get(s['channel'], s['channel'])}</td>"
        f"<td>{e(s['fix'])}</td><td>{s['score_now']} → {s['target_score_12w']}</td></tr>" for s in plan.sequence)
    tg = plan.targets
    first2 = "".join(f"<li>{e(x)}</li>" for x in (nar.get("first_two_weeks") or []))
    return f"""<!doctype html><html><head><meta charset="utf-8"><title>Growth diagnostic — {e(company.name)}</title>
<style>
 @page {{ size: Letter; margin: 20mm 18mm; }}
 body {{ font-family: Helvetica, Arial, sans-serif; color:#141414; font-size:10.5pt; line-height:1.45; margin:0; }}
 h1 {{ font-size:24pt; margin:0 0 2pt; }} h2 {{ font-size:14pt; margin:20pt 0 8pt; border-bottom:2px solid #141414; padding-bottom:3pt; }}
 h3 {{ font-size:12pt; margin:0; }} .muted {{ color:#666; font-size:9.5pt; }}
 .headline {{ font-size:13pt; margin:14pt 0 6pt; }} .overall {{ font-size:36pt; font-weight:700; }}
 .ch {{ margin:12pt 0 14pt; page-break-inside:avoid; }} .head {{ display:flex; justify-content:space-between; align-items:baseline; }}
 .score {{ font-size:18pt; font-weight:700; }} .score span {{ font-size:10pt; color:#666; font-weight:400; }}
 .bar {{ height:6px; background:#eee; border-radius:3px; margin:4pt 0 6pt; }} .fill {{ height:6px; background:#1f4fd1; border-radius:3px; }}
 ul {{ margin:0 0 6pt 16pt; padding:0; }} li {{ margin-bottom:2pt; }} .interp {{ margin:4pt 0; }}
 .fix {{ background:#f3f5fa; border-left:3px solid #1f4fd1; padding:6pt 8pt; margin-top:4pt; }}
 table {{ width:100%; border-collapse:collapse; font-size:9.5pt; }} th,td {{ border:1px solid #ddd; padding:5pt 6pt; text-align:left; vertical-align:top; }} th {{ background:#f3f5fa; }}
 .kpi {{ display:flex; gap:14pt; margin:8pt 0; }} .kpi div {{ background:#f3f5fa; padding:8pt 10pt; border-radius:4px; flex:1; }} .kpi b {{ font-size:16pt; display:block; }}
</style></head><body>
<h1>Growth diagnostic</h1>
<div class="muted">{e(company.name)} · {plan.week_start} · rules {e(plan.rules_version or '')} · generated by the product</div>
<div class="kpi"><div><b>{sc.get('_overall')}</b>overall / 10</div>
<div><b>{tg.get('impressions_icp_weekly', 0):,}</b>est. weekly impressions in ICP today</div>
<div><b>{tg.get('impressions_icp_weekly_12w', 0):,}</b>target by week 12</div></div>
<p class="headline"><strong>{e(nar.get('headline') or '')}</strong></p>
<p>{e(nar.get('summary') or '')}</p>
<h2>Five channels</h2>{rows}
<h2>90-day sequence</h2>
<table><tr><th>When</th><th>Channel</th><th>What ships</th><th>Score now → target</th></tr>{seq_rows}</table>
<h2>First two weeks</h2><ol>{first2}</ol>
<p class="muted">Scores come from versioned rules over connected accounts, the site and the ICP; the narrative interprets them. One number is reported every Friday: impressions inside the ICP.</p>
</body></html>"""


def html_to_pdf(html: str) -> bytes:
    with tempfile.TemporaryDirectory() as d:
        src, out = os.path.join(d, "in.html"), os.path.join(d, "out.pdf")
        open(src, "w").write(html)
        script = f"""
const {{ chromium }} = require('playwright');
(async () => {{
  const b = await chromium.launch({{ executablePath: process.env.CHROMIUM_PATH || undefined, args:['--no-sandbox'] }});
  const p = await b.newPage(); await p.goto('file://{src}');
  await p.pdf({{ path: '{out}', format: 'Letter', printBackground: true }}); await b.close();
}})();"""
        js = os.path.join(d, "r.js")
        open(js, "w").write(script)
        subprocess.run(["node", js], check=True, cwd=os.environ.get("PLAYWRIGHT_CWD", os.getcwd()), timeout=60)
        return open(out, "rb").read()
